# Generated by Django 4.2.14 on 2024-07-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="apellido",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nombre",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="personas",
            name="apellido",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="personas",
            name="nombre",
            field=models.CharField(max_length=150),
        ),
    ]
